### ISSUE TITLE
On 'EXIT', nodes are only removed from connections, not from membership

### ISSUE THREAD

**Issue by vitorenesduarte** [lasp-lang/partisan#48] opened 2017-05-15 16:45 UTC

**Comment by cmeiklejohn** [comment] 2017-05-15 20:11
Which backends is this an issue for?  (also, 'EXIT' signals a disconnection from the node that is connected, so isn't this correct behavior?  ie. a failure doesn't mean the node is no longer part of the cluster, necessarily, right?)

**Comment by vitorenesduarte** [comment] 2017-05-15 20:21
Not sure.
But calling `members()` returns a list of nodes that I expect to be able to send a message.
And it's not the case, currently.

**Comment by lrascao** [comment] 2017-05-19 23:30
The problem is (at least) in the hyparview manager, `connections` is a dict of `Name :: atom() -> Pid :: pid()` while the active/passive view dicts are `{node(), ip(), port()}`. On 'EXIT' the peer is not removed from the active view due to `is_in_active_view` returning false due to this key mismatch.

**Comment by ZGF4** [comment] 2017-05-22 19:49
I'm seeing this with partisan_default_peer_service_manager

**Comment by cmeiklejohn** [comment] 2017-05-23 09:06
I propose extending the API with a `connected_members()` call that returns membership filtered by connected nodes.  Thoughts?

**Comment by lrascao** [comment] 2017-05-23 11:02
That might be a possibility, but my suggestion is to first clear up the thing i mentioned above, it's currently the reason why disconnected nodes are not being removed from the active view (at least in hyparview manager)

**Comment by cmeiklejohn** [comment] 2017-05-23 12:02
The original bug was filed against the static manager, I think.  That's why I had asked clarifications earlier about which backends exhibit this behavior, because I'm not yet convinced the fix is the same for all of th backends.

**Comment by lrascao** [comment] 2017-05-23 23:06
Indeed it's not, all the backends have different behaviour `on_down`: `default` invokes a user defined function, `static` and  `client_server` simply remove the connection from their state and `hyparview` doesn't remove the downed node from the active view

**Comment by cmeiklejohn** [comment] 2017-05-25 09:55
Would you be willing to submit a PR for that change?  I, unfortunately, do not have time at the moment to make these modifications.

**Comment by lrascao** [comment] 2017-05-25 10:07
sure, i got something cooking already, only for the `hyparview` manager though (which is the one i'm interested in)

**Comment by lrascao** [comment] 2017-08-05 17:12
this can closed via #58

**Closed** 2017-08-06 22:56 UTC
